### ISSUE TITLE
Followed instructions on website, OpenSiv3D(0.6.4)Web project template does not build out of the box in Visual Studio 2022

### ISSUE THREAD

**Issue by bluntcoder** [nokotan/OpenSiv3D#12] opened 2022-05-30 01:25 UTC
**エラーの内容 | Followed instructions on website, OpenSiv3D(0.6.4)Web does not build out of the box

**再現方法 | To Reproduce**
1. Followed https://siv3d.kamenokosoft.com/building/overview exactly.
2. Error build output: 
`1>emcc : error : Siv3DScript: No such file or directory ("Siv3DScript" was expected to be an input file, based on the commandline arguments provided)
1>Done building project "openSiv3Dv0_6ForWebTest.vcxproj" -- FAILED.` 

**ビルド環境 | Develop environment (please complete the following information):**
 - OS: Windows 10
 - 開発環境 | IDE: Visual Studio 2022 (new install)

**備考 | Additional context**
Also did a search, there is file that was installed that has that name. Closest is: libSiv3DScript.a, but that's of course a linux library. Is there a build step missing in your instructions?

**Comment by nokotan** [comment] 2022-07-05 14:58
Maybe related: [Additional Library Directories tab doesn't do anything](https://github.com/nokotan/VSExtForEmscripten/issues/11)
This problem has still not been reproduced in my development environment.

**Comment by bluntcoder** [comment] 2022-07-05 22:08
What do you suggest as next steps?

**Comment by nokotan** [comment] 2022-08-03 05:52
This issue may be fixed in [VsExtForEmscripten v0.7.0](https://github.com/nokotan/VSExtForEmscripten/releases/tag/v0.7.0), which includes <https://github.com/nokotan/VSExtForEmscripten/commit/40d4faba1020b389681bf0fd78e50d71214b213e>.

**Comment by nokotan** [comment] 2022-10-23 05:34
This issue has been closed as stale because it does not have recent activity. Feel free to reopen this issue as you needed.

**Closed as completed by nokotan** 2022-10-23 05:34 UTC
Labels: build time error
